\
PARAM_SYNONYMS = {
    "Glucose, Fasting": [
        "Fasting Glucose",
        "Fasting Blood Sugar",
        "Glucose (Fasting)",
        "FBS",
        "Plasma Glucose Fasting",
        "Fasting Plasma Glucose",
        "Glucose - Fasting",
        "Fasting Blood Glucose",
        "Blood Glucose (Fasting)",
        "Fasting Sugar",
        "Glucose Fasting",
        "FBS (Fasting Blood Sugar)",
        "Fasting Glucose Level",
        "Plasma Glucose (Fasting)",
    ],
    "Hba1c (Glycosylated Hemoglobin)": [
        "HbA1c",
        "Glycosylated Hemoglobin",
        "Glycated hemoglobin",
        "Hb A1c",
        "HbA1c (Glycosylated Hemoglobin)",
        "Glycosylated Hemoglobin (HbA1c)",
        "Hemoglobin A1c",
        "HbA1c Level",
        "Glycated Hemoglobin A1c",
        "Hemoglobin A1C",
        "Hb A1C",
        "A1C",
        "A1c",
        "Glycohemoglobin",
        "Glycated Hb",
        "HbA1c Test",
    ],
    "Serum Creatinine": [
        "Creatinine",
        "S. Creatinine",
        "Serum Creatinine",
        "Creatinine Level",
        "Blood Creatinine",
        "Serum Creatinine Level",
        "Creatinine (Serum)",
        "S Creatinine",
        "Creatinine Test",
        "Serum Cr",
        "Blood Cr",
    ],
    "GFR, ESTIMATED": [
        "eGFR",
        "GFR Estimated",
        "Estimated GFR",
        "Glomerular Filtration Rate (estimated)",
        "Glomerular Filtration Rate",
        "GFR",
        "eGFR (estimated)",
        "Estimated Glomerular Filtration Rate",
        "Glomerular Filtration Rate (eGFR)",
        "Kidney Function",
        "Renal Function",
        "GFR (estimated)",
        "Estimated GFR (eGFR)",
    ],
    "HS-CRP (HIGH SENSITIVITY C-REACTIVE PROTEIN)": [
        "HS-CRP",
        "High Sensitivity CRP",
        "CRP (High Sensitivity)",
        "Hs CRP",
    ],
    "Total Cholesterol": [
        "Cholesterol Total",
        "TC",
        "Total Cholesterol",
        "Cholesterol - Total",
        "Total Chol",
        "Cholesterol Level",
        "Serum Total Cholesterol",
        "Blood Cholesterol",
        "Total Cholesterol Level",
        "Chol Total",
        "Cholesterol (Total)",
    ],
    "Serum Triglycerides": [
        "Triglycerides",
        "TG",
    ],
    "Serum HDL Cholesterol": [
        "HDL Cholesterol",
        "HDL",
        "HDL - Cholesterol",
        "Cholesterol - HDL",
        "HDL Chol",
        "High Density Lipoprotein",
        "HDL Level",
        "Serum HDL",
        "HDL (High Density Lipoprotein)",
        "Good Cholesterol",
        "HDL Cholesterol Level",
    ],
    "Serum LDL Cholesterol": [
        "LDL Cholesterol",
        "LDL",
        "Calculated LDL",
        "LDL - Cholesterol",
        "Cholesterol - LDL",
        "LDL Chol",
        "Low Density Lipoprotein",
        "LDL Level",
        "Serum LDL",
        "LDL (Low Density Lipoprotein)",
        "Bad Cholesterol",
        "LDL Cholesterol Level",
        "LDL-C",
    ],
    "Serum VLDL Cholesterol": [
        "VLDL Cholesterol",
        "VLDL",
    ],
    "Serum Calcium": [
        "Calcium",
        "S. Calcium",
    ],
    "Serum Phosphorus": [
        "Phosphorus",
        "Phosphate",
        "S. Phosphorus",
    ],
    "Serum Uric Acid": [
        "Uric Acid",
        "S. Uric Acid",
    ],
    "VITAMIN D (25 - OH VITAMIN D)": [
        "Vitamin D",
        "25-OH Vitamin D",
        "25 OH Vit D",
        "25 Hydroxy Vitamin D",
    ],
    "VITAMIN B12": [
        "Vitamin B12",
        "Vit B12",
    ],
    "Thyroid Stimulating Hormone (TSH)-Ultrasensitive": [
        "TSH",
        "Thyroid Stimulating Hormone",
        "TSH - Ultrasensitive",
        "Thyroid Stimulating Hormone - Ultrasensitive",
        "TSH Ultrasensitive",
        "Ultra Sensitive TSH",
        "TSH Level",
        "Thyroid Function Test",
    ],
    "Hemoglobin": [
        "Hemoglobin",
        "Hb",
        "HGB",
        "Haemoglobin",
        "Hemoglobin Level",
        "Blood Hemoglobin",
        "Hb Level",
        "Hemoglobin (HB)",
        "HGB Level",
    ],
    "Hematocrit": [
        "Hematocrit",
        "HCT",
        "PCV",
        "Packed Cell Volume",
        "Hematocrit Level",
        "HCT Level",
        "PCV Level",
    ],
    "Total Protein": [
        "Total Protein",
        "Protein Total",
        "Serum Total Protein",
        "Total Protein Level",
        "Protein Level",
        "Serum Protein",
    ],
    "Serum Albumin": [
        "Albumin",
        "Serum Albumin",
        "Albumin Level",
        "Serum Albumin Level",
        "Albumin (Serum)",
        "S. Albumin",
    ],
    "Serum Sodium": [
        "Sodium",
        "Serum Sodium",
        "Na",
        "Sodium Level",
        "Serum Na",
        "S. Sodium",
        "Blood Sodium",
    ],
    "Serum Potassium": [
        "Potassium",
        "Serum Potassium",
        "K",
        "Potassium Level",
        "Serum K",
        "S. Potassium",
        "Blood Potassium",
    ],
    "Serum Chloride": [
        "Chloride",
        "Serum Chloride",
        "Cl",
        "Chloride Level",
        "Serum Cl",
        "S. Chloride",
        "Blood Chloride",
    ],
    "Blood Urea Nitrogen": [
        "BUN",
        "Blood Urea Nitrogen",
        "Urea Nitrogen",
        "BUN Level",
        "Blood Urea",
        "Urea",
        "BUN (Blood Urea Nitrogen)",
    ],
    "Aspartate Aminotransferase (AST)": [
        "AST",
        "Aspartate Aminotransferase",
        "SGOT",
        "Aspartate Transaminase",
        "AST Level",
        "SGOT Level",
        "Aspartate Aminotransferase (SGOT)",
    ],
    "Alanine Aminotransferase (ALT)": [
        "ALT",
        "Alanine Aminotransferase",
        "SGPT",
        "Alanine Transaminase",
        "ALT Level",
        "SGPT Level",
        "Alanine Aminotransferase (SGPT)",
    ],
    "Alkaline Phosphatase": [
        "ALP",
        "Alkaline Phosphatase",
        "Alkaline Phosphatase Level",
        "ALP Level",
        "Serum Alkaline Phosphatase",
    ],
    "Total Bilirubin": [
        "Total Bilirubin",
        "Bilirubin Total",
        "Total Bilirubin Level",
        "Bilirubin - Total",
        "Serum Total Bilirubin",
        "T. Bilirubin",
    ],
    "Direct Bilirubin": [
        "Direct Bilirubin",
        "Bilirubin Direct",
        "Direct Bilirubin Level",
        "Bilirubin - Direct",
        "Serum Direct Bilirubin",
        "D. Bilirubin",
        "Conjugated Bilirubin",
    ],
}
